<span>
    <span>{{ __('Average assessment') }}:&nbsp;</span>
    @if($content['type']['shortname'] === 'screening-item')
        <i class="bi-{{ $project->getIconName($values['mean']['positive']) }} me-1" title="<b>{{ __('Positive Effects') }}:</b><br>{{ number_format($values['mean']['positive'], 1) . ' (' . $project->impactToString($values['mean']['positive']) . ')' }}" data-toggle="tooltip" data-bs-custom-class="custom-tooltip" data-bs-delay='{"show":"100", "hide":"0"}' data-bs-html="true" style="color: {{ $project->getPositiveIconColor($values['mean']['positive']) }}; font-size: 0.8rem; vertical-align: middle;"></i>
        <i class="bi-{{ $project->getIconName($values['mean']['negative']) }} me-1" title="<b>{{ __('Negative Effects') }}:</b><br>{{ number_format($values['mean']['negative'], 1) . ' (' . $project->impactToString($values['mean']['negative']) . ')' }}" data-toggle="tooltip" data-bs-custom-class="custom-tooltip" data-bs-delay='{"show":"100", "hide":"0"}' data-bs-html="true" style="color: {{ $project->getNegativeIconColor($values['mean']['negative']) }}; font-size: 0.8rem; vertical-align: middle;"></i>
        <i class="bi-{{ $project->getIconName($values['mean']['potential']) }}" title="{{ $project->getPotentialIconTooltip($values['mean']) }}" data-toggle="tooltip" data-bs-custom-class="custom-tooltip" data-bs-delay='{"show":"100", "hide":"0"}' data-bs-html="true" style="color: {{ $project->getPotentialIconColor($values['mean']['potential']) }}; font-size: 0.8rem; vertical-align: middle;"></i>
    @elseif($content['type']['shortname'] === 'vulnerable-group-item')
        <i class="bi-{{ $project->getIconName($values['mean']['positive']) }} me-1" title="{{ $project->getPositiveIconTooltip($values['mean']) }}" data-toggle="tooltip" data-bs-custom-class="custom-tooltip" data-bs-delay='{"show":"100", "hide":"0"}' data-bs-html="true" style="color: {{ $project->getPositiveIconColor($values['mean']['positive']) }}; font-size: 0.8rem; vertical-align: middle;"></i>
        <i class="bi-{{ $project->getIconName($values['mean']['negative']) }}" title="{{ $project->getNegativeIconTooltip($values['mean']) }}" data-toggle="tooltip" data-bs-custom-class="custom-tooltip" data-bs-delay='{"show":"100", "hide":"0"}' data-bs-html="true" style="color: {{ $project->getNegativeIconColor($values['mean']['negative']) }}; font-size: 0.8rem; vertical-align: middle;"></i>
    @endif
</span>
